services:
  kvartal:
    image: ghcr.io/ScuttleSE/kvartal:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FEED_URL=${FEED_URL}
      - CACHE_TTL=${CACHE_TTL:-600}
      - MIN_SHOW_SIZE=${MIN_SHOW_SIZE:-5}
